import { NextRequest, NextResponse } from "next/server";
import { getSheetData, appendRow } from "@/lib/google-sheets";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const {
      rollNumber,
      studentName,
      campusName,
      enrollmentDate,
      shift,
      grade,
      roomNumber,
      facilitator,
      claimedAge,
      gender,
      isOrphan,
      deceasedParents,
      medicalConditionCategory,
      specifyMedicalCondition,
      doesStudentWork,
      studentWorkDetails,
      careerGoals,
      hobbies,
      ooscClassification,
      lastSchoolAttended,
      lastGradeCompleted,
      reasonForOos,
      religion,
      nationality,
      fatherName,
      relationship,
      fatherEducation,
      fatherProfession,
      fatherIncome,
      fatherCnic,
      fatherCnicCheck,
      numberOfSiblings,
      parentContactNumber,
      parentContactNumberCheck,
      motherName,
      motherEducation,
      motherProfession,
      motherIncome,
      motherCnic,
      motherCnicCheck,
      homeAddress,
      distanceToLearningCentre,
      emergencyContactName,
      emergencyContactNumber,
      highestLevelDocument,
      documentSubmitted,
      bFormNumber,
      bFormNumberCheck,
      dobOnBForm,
      currentAgeBForm,
      studentPictureUploaded,
      bFormUploaded,
      providedUniform,
      providedBooks,
      providedWorkbooks,
      studentProfileSorted,
      studentStatus30Days,
      enrollmentMonth,
      monthsSinceEnrollment,
      enrollmentWeek,
      firstAttended,
      lastAttended,
    } = body;

    if (!rollNumber || !studentName) {
      return NextResponse.json(
        { error: "Roll number and Student name are required" },
        { status: 400 }
      );
    }

    const rowData = [
      enrollmentDate || "",
      shift || "",
      grade || "",
      roomNumber || "",
      facilitator || "",
      claimedAge || "",
      gender || "",
      isOrphan || "",
      deceasedParents || "",
      medicalConditionCategory || "",
      specifyMedicalCondition || "",
      doesStudentWork || "",
      studentWorkDetails || "",
      careerGoals || "",
      hobbies || "",
      ooscClassification || "",
      lastSchoolAttended || "",
      lastGradeCompleted || "",
      reasonForOos || "",
      religion || "",
      nationality || "",
      fatherName || "",
      relationship || "",
      fatherEducation || "",
      fatherProfession || "",
      fatherIncome || "",
      fatherCnic || "",
      fatherCnicCheck || "",
      numberOfSiblings || "",
      parentContactNumber || "",
      parentContactNumberCheck || "",
      motherName || "",
      motherEducation || "",
      motherProfession || "",
      motherIncome || "",
      motherCnic || "",
      motherCnicCheck || "",
      homeAddress || "",
      distanceToLearningCentre || "",
      emergencyContactName || "",
      emergencyContactNumber || "",
      highestLevelDocument || "",
      documentSubmitted || "",
      bFormNumber || "",
      bFormNumberCheck || "",
      dobOnBForm || "",
      currentAgeBForm || "",
      studentPictureUploaded || "",
      bFormUploaded || "",
      providedUniform || "",
      providedBooks || "",
      providedWorkbooks || "",
      studentProfileSorted || "",
      studentStatus30Days || "",
      enrollmentMonth || "",
      monthsSinceEnrollment || "",
      enrollmentWeek || "",
      firstAttended || "",
      lastAttended || "",
      rollNumber,
      studentName,
      campusName || ""
    ];

    await appendRow("Enrollment data!A:BJ", rowData);

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Error creating enrollment:", error);
    return NextResponse.json(
      { error: "Failed to create enrollment record" },
      { status: 500 }
    );
  }
}
